### ISSUE TITLE
[Bug] If i withdraw a candidate the documents i had uploaded remain in form

### ISSUE THREAD

**Issue by overeha** [code4romania/votong#131]
After i have withdrawn a candidate I am taken back to the Edit candidate view. all the input fields are cleared but all the upload fields are still featuring the document names i had uploaded before. They do not dissappear after refresh either. 

![image](https://user-images.githubusercontent.com/45068169/95206199-1375d680-07ef-11eb-85bd-32f620923966.png)

**Comment by aramboi** [comment]
The warning message when withdrawing a candidate should also warn that all candidate related data will be cleared as well.

**Comment by catileptic** [comment]
We have decided to keep only one call to action: "Retrage candidat". 
The effect is that, if a user approves the modal informing them that they will lose all the "susținere", the data associated to the candidate will be cleared from the form and they are presented with an empty form.

This should not delete the candidate data from the DB. We should preserve all candidates in a separate data model.
