### ISSUE TITLE
Wrong title displayed in Admin comisie

### ISSUE THREAD

**Issue by overeha** [code4romania/votong#139]
The H1 should say Candidati selectati, not rejected

![image](https://user-images.githubusercontent.com/45068169/95311807-ca795d00-0896-11eb-8a5e-dd85c041f819.png)

**Comment by AbhishekKakad12** [comment]
I am New to open source work, I will try to  solve this issue.

**Comment by beluamat29** [comment]
Hi! could you please assign this one to me?
