### ISSUE TITLE
[FE] Change text in Elections page and style the Methodology button differently

### ISSUE THREAD

**Issue by overeha** [code4romania/votong#144]
1. **The title that is displayed [in this page ](https://votong.ro/ro/candidati/)needs to be 
"Alegeri Consiliul Economic și Social" instead of Alegeri CES. 
The menu item remains Alegeri CES.** 

**Text (replace the entire paragraph above the line**

Consiliul Economic şi Social este un organism cu rol consultativ în ceea ce privește stabilirea strategiilor şi politicilor economice şi sociale la nivel naţional şi este cheia pentru realizarea, promovarea şi dezvoltarea dialogului și a solidarităţii sociale. Membrii Consiliului au printre atribuții analizarea și avizarea proiectelor de hotărâri și de ordonanțe ale Guvernului și proiectele de lege care urmează să ajungă în Parlament, precum și a proiectelor de programe și strategii înainte de adoptare. Tot membrii CES sunt responsabili și de semnalarea către Guvern și Parlament a unor fenomene sociale și economice care trebuie să ajungă pe agenda pentru a fi întâmpinate de propuneri de acte normative. Nu în ultimul rând, acest Consiliu are un rol activ în analizarea stărilor conflictuale la nivel național sau în sector și propun modalități pentru a le soluționa, conduce analize și studii privind realitatea economică și socială din România și contribuie la implementarea de strategii, programe și standarde în ceea ce privește dialogul social. 

Este esențial să marcăm faptul că anul 2020 este cu atât mai important pentru societatea civilă cu cât este pentru prima dată când conducerea Comitetului Economic și Social ajunge, prin rotație, să fie asigurată de unul din cei 15 reprezentanți al sectorului în acest organism. Este un moment în care sectorul ONG din România are șansa de a demonstra din nou gradul ridicat de profesionalism și competențele sale la cel mai înalt nivel.

Puteți naviga prin cele șase secțiuni de mai jos pentru a analiza candidaturile anunțate, pentru a vă declara susținerea pentru unul sau mai mulți dintre candidați și, apoi, după validarea acestora, vă puteți exprima voturile finale. Mai multe detalii despre Regulament puteți găsi accesând butonul ”Metodologie” de mai jos.

2. **Style this link to look like the rest of the buttons in this platform.** 
![image](https://user-images.githubusercontent.com/45068169/95452279-b0f91380-0971-11eb-9c6a-7847d458b8b7.png)

button sample
![image](https://user-images.githubusercontent.com/45068169/95452797-7ba0f580-0972-11eb-8cc6-6fa394cc21d2.png)

**Comment by Utwo** [comment]
I can take this
