### ISSUE TITLE
[FE] Center branding on footer, increase size and change text 

### ISSUE THREAD

**Issue by overeha** [code4romania/votong#148]
Please change the branding in footer to look like like this: 
Text: ”Soluție proiectată, dezvoltată și administrată pro-bono de”

![image](https://user-images.githubusercontent.com/45068169/95454069-9b391d80-0974-11eb-9d52-b180562bb034.png)

**Comment by AbhishekKakad12** [comment]
I am new to open source work, Can I work on this issue?

**Comment by catileptic** [comment]
@AbhishekKakad12 yes, you can. :)
