### ISSUE TITLE
[Bug] Reload does not clear uploaded files from form

### ISSUE THREAD

**Issue by overeha** [code4romania/votong#154]
If I fill in a Registration form and i get a recaptcha error (or any kind of error) the forms remembers all the other fields i have filled in upon my first registration. Which is false, because the files I have attached are no longer attached and i should reattach them. This is misleading because users attempt to send repeatedly the same form with no files attached because the front end tells them that the docs are actually attached.

![image](https://user-images.githubusercontent.com/45068169/95557214-2372fd80-0a1d-11eb-818e-cb4d10a6863c.png)

**Comment by catileptic** [comment]
The Captcha system has been switched to V2 so we can't end up in a scenario where a user can click submit without passing the challenge, so this won't reproduce anymore. I'm closing it and we can re-open it if the bug manifests.

**Comment by aramboi** [comment]
Merging the above PR will also make the browser prompt the user that the other required fields are needed as well without making a round trip to the server for that.
