### ISSUE TITLE
[FE] Add two new cards on the homepage

### ISSUE THREAD

**Issue by overeha** [code4romania/votong#156]
Please add one more cards row in the homepage. Find below the text for every card as well as the extra icon needed in the design. 
The last card should be styled differently. 

See mock here:

![image](https://user-images.githubusercontent.com/45068169/95903305-a4742100-0d9e-11eb-951d-958ec19dbac7.png)

**Texte:**

**Card 1:** 
Pasul 1: Eligibilitate
Se pot înscrie în platformă toate asociațiile, fundațile sau federațiile înregistrate legal în România, orice fundație pentru tineret sau Fundația Națională pentru Tineret, precum și Societatea Națională de Cruce Roșie din România și a structurilor sale cu personalitate juridică, care respectă condițiile din regulament.

**Card 2:** 
Pasul 2: Înscriere
Organizațiile se pot înscrie  în platformă cu ajutorul unui formular simplu disponibil în meniul acestei platforme. Pentru a intra în VotONG există o serie de condiții prestabilite care trebuiesc îndeplinite și care pot fi consultate în Regulamentul platformei. 

**Card 3:**
Pasul 3: Validare
După înscriere fiecare ONG este validat. Administratorul platformei va verifica informațiile prezentate în formularul completat și va contacta organizația dacă sunt necesare și alte documente. Validarea organizațiilor înscrise va avea loc anual. 

**Card 4:**
Pasul 4: Vot
Dacă există alegeri în curs, fiecare ONG care se califică, potrivit regulamentului fiecărei runde, poate să propună candidaturi pentru a intra în cursa electorală. Organizațiile pot de asemenea și să își exprime susținerea pentru candidați.

**Card 5:**
Pasul 5: Rezultate
Rezultatele fiecărei runde de alegeri vor fi publicate pe platformă și anunțate prin e-mail către toate organizațiile care au participat la runda de vot.

**Card 6:**
Regulament
Citește aici detalii despre regulamentul de funcționare al platformei Vot ONG. 
Button: Vezi regulament

**ICON for first card**

![0-eligibilitatepng](https://user-images.githubusercontent.com/45068169/95915343-aeeae680-0daf-11eb-8bfc-be2c121cd369.png)

**Comment by surdu** [comment]
@overeha Could you please provide the icon in .svg format? All others are svg.
