### ISSUE TITLE
[nitpick] Quick actions for flags require selecting a flag (even a flag which will not be changed)

### ISSUE THREAD

**Issue by catileptic** [code4romania/votong#208]
**This is a nitpick** and there's no rush with fixing this one. 

In the admin panel (`/admin`), when I want to use a quick action in the Flags menu, in order to change the state of the flags (set some to `True`, set others to `False`), the implementation requires me to select at least one flag before applying a quick action. 

This doesn't make much sense, since I can select `enable_org_registration` and then use the "Set flags for phase 3 - VOTING" quick action, which does not change the flag I selected at all (if the value is already correct). 

For a UX point of view, this is a little counter-intuitive. 
Could the quick actions work without requiring the user to tick any flag?

**Comment by aramboi** [comment]
fixed in #256
