### ISSUE TITLE
Add an extra paragraph in the regulations page

### ISSUE THREAD

**Issue by overeha** [code4romania/votong#230]
Please add the paragraph below [in this page](https://votong.ro/ro/regulamentul_platformei/) 
I will leave the exact place where to insert the paragraph in the first comment of this issue. 

**Cine poate participa la procesul de votare?
Orice
- asociație, fundație sau federație înregistrată legal în România conform OG 26/2000, și/sau Legii 21/1924 privind asociaţiile şi fundaţiile (cu modificările şi completările ulterioare),
- fundație pentru tineret de la nivel județean sau a municipiului București,
s- au Fundația Națională pentru Tineret, înființată în baza legii 146/2002 (cu modificările și completările ulterioare) precum și
Societatea Națională de Cruce Roșie din România înființată în baza Legii 139/1995 (modificată și completată de Legea 524/2004) și a structurilor sale cu personalitate juridică,

care a depus bilanţ contabil în anul premergător celui destinat alegerilor, cu excepția asociațiilor de întreprinzători și a asociațiilor de locatari.Nu sunt eligibile acele organizații în care membrii conducerii organizației (Președinte și Consiliu Director) sunt membri ai conducerii unui partid politic sau persoane care au fost alese într-o funcție publică.

În funcție de specificul rundei electorale, pot fi adăugate criterii suplimentare celor de mai sus, urmând ca organizațiile care nu respectă toate noile criterii să aibă contul dezactivat pe perioada oricărei runde în care nu sunt eligibili pentru a-și exprima votul.**

**Comment by overeha** [comment]
This is where this paragraph should be inserted. 

![votong regulament](https://user-images.githubusercontent.com/45068169/109795933-37afd500-7c20-11eb-9143-f3a91ced4efa.png)

**Comment by catileptic** [comment]
Done
